registrator:
  image: gliderlabs/registrator:latest
  net: host
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  command: consul://localhost:8500

consul:
  image: progrium/consul
  ports:
    - 8400:8400
    - 8500:8500
    - 8600:53/udp
  hostname: node1
  command: -server -bootstrap -ui-dir /ui

www:
  build: www
  environment:
    CONSUL_URL: consul:8500
  ports:
    - 8000:80
    - 8443:443
  links:
    - backend
    - consul

backend:
  build: backend
  ports:
    - 3000:3000
